#!/bin/bash

echo "<html>"
echo "<body>"
echo "<h2>Arguments Passed</h2>"

# Loop through at most 3 arguments
for i in {1..3}; do
  arg=${!i}  # Get the argument using indirect variable reference
  if [ -n "$arg" ]; then
    echo "<p>Argument $i: $arg</p>"
  fi
done

echo "</body>"
echo "</html>"
